### ISSUE TITLE
I can help with the To-Do part.

### ISSUE THREAD

**Issue by MajhiRockzZ** [rudevdr/Udacity-frontend-project-Day-logger#1]
I think it only need a 
1. Text Area for writing the work to do.
2. + Button to add things to list.
3. - Button to delete a particular task.
4. Clear all
That's what i think so.

**Comment by rudevdr** [comment]
@MajhiRockzZ Yes may. But I don't think we should include many features because it will be very hard for beginners.

**Comment by MajhiRockzZ** [comment]
We should start this one by our own self only because. I can see that there are no further people showing any kind of interest on this
