### ISSUE TITLE
Those mock ups from where did you got those. 

### ISSUE THREAD

**Issue by MajhiRockzZ** [rudevdr/Udacity-frontend-project-Day-logger#2]
Have you already worked in this project or just used some of the Mock Up or Illustration tools.

**Comment by rudevdr** [comment]
I made them in inkscape.

**Comment by MajhiRockzZ** [comment]
You idea is practice as you can implement the thing that you are learning in Scholarship program in this directly it's only an work of some good CSS and JavaScript code.

**Comment by rudevdr** [comment]
Yeah I know..I meant I dont have idea if we can involve technology which are not part of the course. Maybe it is allowed.
